name: Hourly Health

on:
  schedule:
    - cron: '0 * * * *'   # hourly
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      WEB_ALIAS: esgnavigator-ai.vercel.app
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Run status check (via Edge /api/internal/status)
        run: node scripts/ping-health.mjs
