name: Post-Deploy Health
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  health:
    runs-on: ubuntu-latest
    env:
      WEB_ALIAS: esgnavigator-ai.vercel.app
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }
      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Health check (uptime → health → CORS)
        run: node scripts/check-health.mjs
